name: Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install chezmoi
        run: sh -c "$(curl -fsLS get.chezmoi.io)"

      - name: Test chezmoi template syntax
        run: |
          cat > chezmoi.toml <<EOF
          [data]
            git_email = "test@example.com"
          EOF

          ./bin/chezmoi execute-template --source $PWD --config chezmoi.toml < dot_gitconfig.tmpl
          ./bin/chezmoi execute-template --source $PWD --config chezmoi.toml < run_onchange_after_10_brew_bundle.sh.tmpl
